[project]
name = "ind-mada"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyterlab>=4.6.4",
    "seaborn>=0.13.2",
    "taipy>=4.1.1",
]

[project.scripts]
ind-mada = "ind_mada:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
